// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucdyglclrqdwypegojrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZHlnbGNscnFkd3lwZWdvanJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMzk1MTIsImV4cCI6MjA1MjYxNTUxMn0.aFcQlGsFBjBSHm3n_GogTq80R_6vdjqAQp2y_AdcEHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);